//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOHATS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cikis
    {
        public int id { get; set; }
        public int dosyano { get; set; }
        public string sevktarihi { get; set; }
        public Nullable<System.DateTime> cikissaati { get; set; }
        public string odeme { get; set; }
        public string toplamtutar { get; set; }
    }
}
