//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOHATS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class hasta
    {
        public string tckimlikno { get; set; }
        public int dosyano { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string dogumyeri { get; set; }
        public Nullable<System.DateTime> dogumtarihi { get; set; }
        public string babaadi { get; set; }
        public string anneadi { get; set; }
        public string cinsiyet { get; set; }
        public string kangrubu { get; set; }
        public string medenihal { get; set; }
        public string adres { get; set; }
        public string tel { get; set; }
        public string kurumsicilno { get; set; }
        public string kurumadi { get; set; }
        public string yakintel { get; set; }
        public string yakinkurumsicilno { get; set; }
        public string yakinkurumadi { get; set; }
    }
}
