//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOHATS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public int kodu { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string sifre { get; set; }
        public string yetki { get; set; }
        public string evtel { get; set; }
        public string ceptel { get; set; }
        public string adres { get; set; }
        public string unvan { get; set; }
        public Nullable<System.DateTime> isebaslama { get; set; }
        public string maas { get; set; }
        public string dogumyeri { get; set; }
        public string annead { get; set; }
        public string babaad { get; set; }
        public string cinsiyet { get; set; }
        public string kangrubu { get; set; }
        public string medenihal { get; set; }
        public Nullable<System.DateTime> dogumtarihi { get; set; }
        public string tckimlikno { get; set; }
        public string username { get; set; }
    }
}
