//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOHATS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class poliklinik
    {
        public int id { get; set; }
        public string poliklinikadi { get; set; }
        public string durum { get; set; }
        public string aciklama { get; set; }
    }
}
