//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOHATS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sevk
    {
        public int id { get; set; }
        public System.DateTime sevktarihi { get; set; }
        public string dosyano { get; set; }
        public string poliklinik { get; set; }
        public string saat { get; set; }
        public string yapilanislem { get; set; }
        public string drkod { get; set; }
        public string miktar { get; set; }
        public string birimfiyat { get; set; }
        public string sira { get; set; }
        public string toplamtutar { get; set; }
        public string taburcu { get; set; }
    }
}
